spring.application.name=gestionale-tennistavolo
spring.config.import=optional:classpath:application-local.properties
spring.datasource.url=jdbc:mysql://localhost:3306/gestionale_tennistavolo
spring.jpa.hibernate.ddl-auto=update